### ISSUE TITLE
Doris Operator Roadmap 🙌🏻

### ISSUE THREAD

**Issue by Al-assad** [linsoss/doris-operator#26]
### Features

- [ ] #32 
- [ ] Suspension and restore mechanism for the Doris cluster.
- [x] Graceful restart mechanism for the Doris cluster components.
  - #31 
- [ ] Improved automatic failover for Doris components: When the number of component Pods failing exceeds the threshold, temporary capacity would be increased to compensate for the replica count.
- [ ] Automatic drop of node metadata from Doris when scaling in FE, BE (Comple Mode) and Broker components.
- [ ] Automatic execution of decommission data operation when scaling in Doris BE (Mixed Mode).
- [ ] Doris cluster data backup CRD & Controller.

### CI/CD

- [ ] Github CI: Automatic build and release of doris-operator image, kustomize and helm packages.
- [ ] Unit testing for Operator Controller.
- [ ] E2E testing for Doris Operator.
